[Export]
baked_state = false
baked_notebookfile = false
offer_binder = true
slider_server_url="https://computationalthinking-sliderserver-droplet.plutojl.org"
ignore_cache = [
    "index.jl",
]
create_index = false
exclude = [
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl",
]

[SliderServer]
port = 80
host = "0.0.0.0"
exclude=[
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl"
]
